/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TicketCategoriesRouteImport } from './routes/ticket-categories'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SprintsRouteImport } from './routes/sprints'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ClientRouteImport } from './routes/client'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ChamadosIndexRouteImport } from './routes/chamados.index'
import { Route as AtividadesIndexRouteImport } from './routes/atividades.index'
import { Route as TicketsNewRouteImport } from './routes/tickets.new'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as TeamsNewRouteImport } from './routes/teams.new'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as SprintsNovaRouteImport } from './routes/sprints.nova'
import { Route as SprintsNewRouteImport } from './routes/sprints.new'
import { Route as SprintsIdRouteImport } from './routes/sprints.$id'
import { Route as ProjetosNovoRouteImport } from './routes/projetos.novo'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as ClientTicketsRouteImport } from './routes/client.tickets'
import { Route as ClientProjectsRouteImport } from './routes/client.projects'
import { Route as ChamadosNovoRouteImport } from './routes/chamados.novo'
import { Route as ChamadosIdRouteImport } from './routes/chamados.$id'
import { Route as BacklogNewRouteImport } from './routes/backlog.new'
import { Route as AtividadesNovaRouteImport } from './routes/atividades.nova'
import { Route as AtividadesIdRouteImport } from './routes/atividades.$id'
import { Route as ActivitiesNewRouteImport } from './routes/activities.new'
import { Route as ActivitiesIdRouteImport } from './routes/activities.$id'
import { Route as TicketsIdEditRouteImport } from './routes/tickets.$id.edit'
import { Route as TeamsIdEditRouteImport } from './routes/teams.$id.edit'
import { Route as SprintsIdEditarRouteImport } from './routes/sprints.$id.editar'
import { Route as SprintsIdEditRouteImport } from './routes/sprints.$id.edit'
import { Route as ProjetosIdEditarRouteImport } from './routes/projetos.$id.editar'
import { Route as ProjectsIdEditRouteImport } from './routes/projects.$id.edit'
import { Route as ClientsIdEditRouteImport } from './routes/clients.$id.edit'
import { Route as ClientTicketsNewRouteImport } from './routes/client.tickets.new'
import { Route as ClientTicketsIdRouteImport } from './routes/client.tickets.$id'
import { Route as ClientProjectsIdRouteImport } from './routes/client.projects.$id'
import { Route as ChamadosIdEditarRouteImport } from './routes/chamados.$id.editar'
import { Route as AtividadesIdEditarRouteImport } from './routes/atividades.$id.editar'
import { Route as ActivitiesIdEditRouteImport } from './routes/activities.$id.edit'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketCategoriesRoute = TicketCategoriesRouteImport.update({
  id: '/ticket-categories',
  path: '/ticket-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintsRoute = SprintsRouteImport.update({
  id: '/sprints',
  path: '/sprints',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosIndexRoute = ChamadosIndexRouteImport.update({
  id: '/chamados/',
  path: '/chamados/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesIndexRoute = AtividadesIndexRouteImport.update({
  id: '/atividades/',
  path: '/atividades/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsNewRoute = TicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TicketsRoute,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketsRoute,
} as any)
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TeamsRoute,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeamsRoute,
} as any)
const SprintsNovaRoute = SprintsNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => SprintsRoute,
} as any)
const SprintsNewRoute = SprintsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SprintsRoute,
} as any)
const SprintsIdRoute = SprintsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SprintsRoute,
} as any)
const ProjetosNovoRoute = ProjetosNovoRouteImport.update({
  id: '/projetos/novo',
  path: '/projetos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientTicketsRoute = ClientTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProjectsRoute = ClientProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ClientRoute,
} as any)
const ChamadosNovoRoute = ChamadosNovoRouteImport.update({
  id: '/chamados/novo',
  path: '/chamados/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosIdRoute = ChamadosIdRouteImport.update({
  id: '/chamados/$id',
  path: '/chamados/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogNewRoute = BacklogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BacklogRoute,
} as any)
const AtividadesNovaRoute = AtividadesNovaRouteImport.update({
  id: '/atividades/nova',
  path: '/atividades/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesIdRoute = AtividadesIdRouteImport.update({
  id: '/atividades/$id',
  path: '/atividades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesNewRoute = ActivitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ActivitiesRoute,
} as any)
const ActivitiesIdRoute = ActivitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ActivitiesRoute,
} as any)
const TicketsIdEditRoute = TicketsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TicketsIdRoute,
} as any)
const TeamsIdEditRoute = TeamsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TeamsIdRoute,
} as any)
const SprintsIdEditarRoute = SprintsIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => SprintsIdRoute,
} as any)
const SprintsIdEditRoute = SprintsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SprintsIdRoute,
} as any)
const ProjetosIdEditarRoute = ProjetosIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ProjetosIdRoute,
} as any)
const ProjectsIdEditRoute = ProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ClientsIdEditRoute = ClientsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ClientsIdRoute,
} as any)
const ClientTicketsNewRoute = ClientTicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClientTicketsRoute,
} as any)
const ClientTicketsIdRoute = ClientTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientTicketsRoute,
} as any)
const ClientProjectsIdRoute = ClientProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientProjectsRoute,
} as any)
const ChamadosIdEditarRoute = ChamadosIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ChamadosIdRoute,
} as any)
const AtividadesIdEditarRoute = AtividadesIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AtividadesIdRoute,
} as any)
const ActivitiesIdEditRoute = ActivitiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ActivitiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/backlog': typeof BacklogRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sprints': typeof SprintsRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/ticket-categories': typeof TicketCategoriesRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/activities/$id': typeof ActivitiesIdRouteWithChildren
  '/activities/new': typeof ActivitiesNewRoute
  '/atividades/$id': typeof AtividadesIdRouteWithChildren
  '/atividades/nova': typeof AtividadesNovaRoute
  '/backlog/new': typeof BacklogNewRoute
  '/chamados/$id': typeof ChamadosIdRouteWithChildren
  '/chamados/novo': typeof ChamadosNovoRoute
  '/client/projects': typeof ClientProjectsRouteWithChildren
  '/client/tickets': typeof ClientTicketsRouteWithChildren
  '/clients/$id': typeof ClientsIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projetos/$id': typeof ProjetosIdRouteWithChildren
  '/projetos/novo': typeof ProjetosNovoRoute
  '/sprints/$id': typeof SprintsIdRouteWithChildren
  '/sprints/new': typeof SprintsNewRoute
  '/sprints/nova': typeof SprintsNovaRoute
  '/teams/$id': typeof TeamsIdRouteWithChildren
  '/teams/new': typeof TeamsNewRoute
  '/tickets/$id': typeof TicketsIdRouteWithChildren
  '/tickets/new': typeof TicketsNewRoute
  '/atividades/': typeof AtividadesIndexRoute
  '/chamados/': typeof ChamadosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/activities/$id/edit': typeof ActivitiesIdEditRoute
  '/atividades/$id/editar': typeof AtividadesIdEditarRoute
  '/chamados/$id/editar': typeof ChamadosIdEditarRoute
  '/client/projects/$id': typeof ClientProjectsIdRoute
  '/client/tickets/$id': typeof ClientTicketsIdRoute
  '/client/tickets/new': typeof ClientTicketsNewRoute
  '/clients/$id/edit': typeof ClientsIdEditRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projetos/$id/editar': typeof ProjetosIdEditarRoute
  '/sprints/$id/edit': typeof SprintsIdEditRoute
  '/sprints/$id/editar': typeof SprintsIdEditarRoute
  '/teams/$id/edit': typeof TeamsIdEditRoute
  '/tickets/$id/edit': typeof TicketsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/backlog': typeof BacklogRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sprints': typeof SprintsRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/ticket-categories': typeof TicketCategoriesRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/activities/$id': typeof ActivitiesIdRouteWithChildren
  '/activities/new': typeof ActivitiesNewRoute
  '/atividades/$id': typeof AtividadesIdRouteWithChildren
  '/atividades/nova': typeof AtividadesNovaRoute
  '/backlog/new': typeof BacklogNewRoute
  '/chamados/$id': typeof ChamadosIdRouteWithChildren
  '/chamados/novo': typeof ChamadosNovoRoute
  '/client/projects': typeof ClientProjectsRouteWithChildren
  '/client/tickets': typeof ClientTicketsRouteWithChildren
  '/clients/$id': typeof ClientsIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projetos/$id': typeof ProjetosIdRouteWithChildren
  '/projetos/novo': typeof ProjetosNovoRoute
  '/sprints/$id': typeof SprintsIdRouteWithChildren
  '/sprints/new': typeof SprintsNewRoute
  '/sprints/nova': typeof SprintsNovaRoute
  '/teams/$id': typeof TeamsIdRouteWithChildren
  '/teams/new': typeof TeamsNewRoute
  '/tickets/$id': typeof TicketsIdRouteWithChildren
  '/tickets/new': typeof TicketsNewRoute
  '/atividades': typeof AtividadesIndexRoute
  '/chamados': typeof ChamadosIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/activities/$id/edit': typeof ActivitiesIdEditRoute
  '/atividades/$id/editar': typeof AtividadesIdEditarRoute
  '/chamados/$id/editar': typeof ChamadosIdEditarRoute
  '/client/projects/$id': typeof ClientProjectsIdRoute
  '/client/tickets/$id': typeof ClientTicketsIdRoute
  '/client/tickets/new': typeof ClientTicketsNewRoute
  '/clients/$id/edit': typeof ClientsIdEditRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projetos/$id/editar': typeof ProjetosIdEditarRoute
  '/sprints/$id/edit': typeof SprintsIdEditRoute
  '/sprints/$id/editar': typeof SprintsIdEditarRoute
  '/teams/$id/edit': typeof TeamsIdEditRoute
  '/tickets/$id/edit': typeof TicketsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/backlog': typeof BacklogRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/kanban': typeof KanbanRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sprints': typeof SprintsRouteWithChildren
  '/teams': typeof TeamsRouteWithChildren
  '/ticket-categories': typeof TicketCategoriesRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/activities/$id': typeof ActivitiesIdRouteWithChildren
  '/activities/new': typeof ActivitiesNewRoute
  '/atividades/$id': typeof AtividadesIdRouteWithChildren
  '/atividades/nova': typeof AtividadesNovaRoute
  '/backlog/new': typeof BacklogNewRoute
  '/chamados/$id': typeof ChamadosIdRouteWithChildren
  '/chamados/novo': typeof ChamadosNovoRoute
  '/client/projects': typeof ClientProjectsRouteWithChildren
  '/client/tickets': typeof ClientTicketsRouteWithChildren
  '/clients/$id': typeof ClientsIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projetos/$id': typeof ProjetosIdRouteWithChildren
  '/projetos/novo': typeof ProjetosNovoRoute
  '/sprints/$id': typeof SprintsIdRouteWithChildren
  '/sprints/new': typeof SprintsNewRoute
  '/sprints/nova': typeof SprintsNovaRoute
  '/teams/$id': typeof TeamsIdRouteWithChildren
  '/teams/new': typeof TeamsNewRoute
  '/tickets/$id': typeof TicketsIdRouteWithChildren
  '/tickets/new': typeof TicketsNewRoute
  '/atividades/': typeof AtividadesIndexRoute
  '/chamados/': typeof ChamadosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/activities/$id/edit': typeof ActivitiesIdEditRoute
  '/atividades/$id/editar': typeof AtividadesIdEditarRoute
  '/chamados/$id/editar': typeof ChamadosIdEditarRoute
  '/client/projects/$id': typeof ClientProjectsIdRoute
  '/client/tickets/$id': typeof ClientTicketsIdRoute
  '/client/tickets/new': typeof ClientTicketsNewRoute
  '/clients/$id/edit': typeof ClientsIdEditRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projetos/$id/editar': typeof ProjetosIdEditarRoute
  '/sprints/$id/edit': typeof SprintsIdEditRoute
  '/sprints/$id/editar': typeof SprintsIdEditarRoute
  '/teams/$id/edit': typeof TeamsIdEditRoute
  '/tickets/$id/edit': typeof TicketsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/backlog'
    | '/client'
    | '/clients'
    | '/kanban'
    | '/login'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/sprints'
    | '/teams'
    | '/ticket-categories'
    | '/tickets'
    | '/activities/$id'
    | '/activities/new'
    | '/atividades/$id'
    | '/atividades/nova'
    | '/backlog/new'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/client/projects'
    | '/client/tickets'
    | '/clients/$id'
    | '/clients/new'
    | '/projects/$id'
    | '/projects/new'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/sprints/$id'
    | '/sprints/new'
    | '/sprints/nova'
    | '/teams/$id'
    | '/teams/new'
    | '/tickets/$id'
    | '/tickets/new'
    | '/atividades/'
    | '/chamados/'
    | '/projetos/'
    | '/activities/$id/edit'
    | '/atividades/$id/editar'
    | '/chamados/$id/editar'
    | '/client/projects/$id'
    | '/client/tickets/$id'
    | '/client/tickets/new'
    | '/clients/$id/edit'
    | '/projects/$id/edit'
    | '/projetos/$id/editar'
    | '/sprints/$id/edit'
    | '/sprints/$id/editar'
    | '/teams/$id/edit'
    | '/tickets/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/backlog'
    | '/client'
    | '/clients'
    | '/kanban'
    | '/login'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/sprints'
    | '/teams'
    | '/ticket-categories'
    | '/tickets'
    | '/activities/$id'
    | '/activities/new'
    | '/atividades/$id'
    | '/atividades/nova'
    | '/backlog/new'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/client/projects'
    | '/client/tickets'
    | '/clients/$id'
    | '/clients/new'
    | '/projects/$id'
    | '/projects/new'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/sprints/$id'
    | '/sprints/new'
    | '/sprints/nova'
    | '/teams/$id'
    | '/teams/new'
    | '/tickets/$id'
    | '/tickets/new'
    | '/atividades'
    | '/chamados'
    | '/projetos'
    | '/activities/$id/edit'
    | '/atividades/$id/editar'
    | '/chamados/$id/editar'
    | '/client/projects/$id'
    | '/client/tickets/$id'
    | '/client/tickets/new'
    | '/clients/$id/edit'
    | '/projects/$id/edit'
    | '/projetos/$id/editar'
    | '/sprints/$id/edit'
    | '/sprints/$id/editar'
    | '/teams/$id/edit'
    | '/tickets/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/backlog'
    | '/client'
    | '/clients'
    | '/kanban'
    | '/login'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/sprints'
    | '/teams'
    | '/ticket-categories'
    | '/tickets'
    | '/activities/$id'
    | '/activities/new'
    | '/atividades/$id'
    | '/atividades/nova'
    | '/backlog/new'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/client/projects'
    | '/client/tickets'
    | '/clients/$id'
    | '/clients/new'
    | '/projects/$id'
    | '/projects/new'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/sprints/$id'
    | '/sprints/new'
    | '/sprints/nova'
    | '/teams/$id'
    | '/teams/new'
    | '/tickets/$id'
    | '/tickets/new'
    | '/atividades/'
    | '/chamados/'
    | '/projetos/'
    | '/activities/$id/edit'
    | '/atividades/$id/editar'
    | '/chamados/$id/editar'
    | '/client/projects/$id'
    | '/client/tickets/$id'
    | '/client/tickets/new'
    | '/clients/$id/edit'
    | '/projects/$id/edit'
    | '/projetos/$id/editar'
    | '/sprints/$id/edit'
    | '/sprints/$id/editar'
    | '/teams/$id/edit'
    | '/tickets/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRouteWithChildren
  BacklogRoute: typeof BacklogRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  ClientsRoute: typeof ClientsRouteWithChildren
  KanbanRoute: typeof KanbanRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SprintsRoute: typeof SprintsRouteWithChildren
  TeamsRoute: typeof TeamsRouteWithChildren
  TicketCategoriesRoute: typeof TicketCategoriesRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  AtividadesIdRoute: typeof AtividadesIdRouteWithChildren
  AtividadesNovaRoute: typeof AtividadesNovaRoute
  ChamadosIdRoute: typeof ChamadosIdRouteWithChildren
  ChamadosNovoRoute: typeof ChamadosNovoRoute
  ProjetosIdRoute: typeof ProjetosIdRouteWithChildren
  ProjetosNovoRoute: typeof ProjetosNovoRoute
  AtividadesIndexRoute: typeof AtividadesIndexRoute
  ChamadosIndexRoute: typeof ChamadosIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket-categories': {
      id: '/ticket-categories'
      path: '/ticket-categories'
      fullPath: '/ticket-categories'
      preLoaderRoute: typeof TicketCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprints': {
      id: '/sprints'
      path: '/sprints'
      fullPath: '/sprints'
      preLoaderRoute: typeof SprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados/': {
      id: '/chamados/'
      path: '/chamados'
      fullPath: '/chamados/'
      preLoaderRoute: typeof ChamadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/': {
      id: '/atividades/'
      path: '/atividades'
      fullPath: '/atividades/'
      preLoaderRoute: typeof AtividadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/new': {
      id: '/tickets/new'
      path: '/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof TicketsNewRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/teams/new': {
      id: '/teams/new'
      path: '/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof TeamsNewRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/sprints/nova': {
      id: '/sprints/nova'
      path: '/nova'
      fullPath: '/sprints/nova'
      preLoaderRoute: typeof SprintsNovaRouteImport
      parentRoute: typeof SprintsRoute
    }
    '/sprints/new': {
      id: '/sprints/new'
      path: '/new'
      fullPath: '/sprints/new'
      preLoaderRoute: typeof SprintsNewRouteImport
      parentRoute: typeof SprintsRoute
    }
    '/sprints/$id': {
      id: '/sprints/$id'
      path: '/$id'
      fullPath: '/sprints/$id'
      preLoaderRoute: typeof SprintsIdRouteImport
      parentRoute: typeof SprintsRoute
    }
    '/projetos/novo': {
      id: '/projetos/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof ProjetosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/client/tickets': {
      id: '/client/tickets'
      path: '/tickets'
      fullPath: '/client/tickets'
      preLoaderRoute: typeof ClientTicketsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/projects': {
      id: '/client/projects'
      path: '/projects'
      fullPath: '/client/projects'
      preLoaderRoute: typeof ClientProjectsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/chamados/novo': {
      id: '/chamados/novo'
      path: '/chamados/novo'
      fullPath: '/chamados/novo'
      preLoaderRoute: typeof ChamadosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados/$id': {
      id: '/chamados/$id'
      path: '/chamados/$id'
      fullPath: '/chamados/$id'
      preLoaderRoute: typeof ChamadosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog/new': {
      id: '/backlog/new'
      path: '/new'
      fullPath: '/backlog/new'
      preLoaderRoute: typeof BacklogNewRouteImport
      parentRoute: typeof BacklogRoute
    }
    '/atividades/nova': {
      id: '/atividades/nova'
      path: '/atividades/nova'
      fullPath: '/atividades/nova'
      preLoaderRoute: typeof AtividadesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/$id': {
      id: '/atividades/$id'
      path: '/atividades/$id'
      fullPath: '/atividades/$id'
      preLoaderRoute: typeof AtividadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/new': {
      id: '/activities/new'
      path: '/new'
      fullPath: '/activities/new'
      preLoaderRoute: typeof ActivitiesNewRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/activities/$id': {
      id: '/activities/$id'
      path: '/$id'
      fullPath: '/activities/$id'
      preLoaderRoute: typeof ActivitiesIdRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/tickets/$id/edit': {
      id: '/tickets/$id/edit'
      path: '/edit'
      fullPath: '/tickets/$id/edit'
      preLoaderRoute: typeof TicketsIdEditRouteImport
      parentRoute: typeof TicketsIdRoute
    }
    '/teams/$id/edit': {
      id: '/teams/$id/edit'
      path: '/edit'
      fullPath: '/teams/$id/edit'
      preLoaderRoute: typeof TeamsIdEditRouteImport
      parentRoute: typeof TeamsIdRoute
    }
    '/sprints/$id/editar': {
      id: '/sprints/$id/editar'
      path: '/editar'
      fullPath: '/sprints/$id/editar'
      preLoaderRoute: typeof SprintsIdEditarRouteImport
      parentRoute: typeof SprintsIdRoute
    }
    '/sprints/$id/edit': {
      id: '/sprints/$id/edit'
      path: '/edit'
      fullPath: '/sprints/$id/edit'
      preLoaderRoute: typeof SprintsIdEditRouteImport
      parentRoute: typeof SprintsIdRoute
    }
    '/projetos/$id/editar': {
      id: '/projetos/$id/editar'
      path: '/editar'
      fullPath: '/projetos/$id/editar'
      preLoaderRoute: typeof ProjetosIdEditarRouteImport
      parentRoute: typeof ProjetosIdRoute
    }
    '/projects/$id/edit': {
      id: '/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof ProjectsIdEditRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/clients/$id/edit': {
      id: '/clients/$id/edit'
      path: '/edit'
      fullPath: '/clients/$id/edit'
      preLoaderRoute: typeof ClientsIdEditRouteImport
      parentRoute: typeof ClientsIdRoute
    }
    '/client/tickets/new': {
      id: '/client/tickets/new'
      path: '/new'
      fullPath: '/client/tickets/new'
      preLoaderRoute: typeof ClientTicketsNewRouteImport
      parentRoute: typeof ClientTicketsRoute
    }
    '/client/tickets/$id': {
      id: '/client/tickets/$id'
      path: '/$id'
      fullPath: '/client/tickets/$id'
      preLoaderRoute: typeof ClientTicketsIdRouteImport
      parentRoute: typeof ClientTicketsRoute
    }
    '/client/projects/$id': {
      id: '/client/projects/$id'
      path: '/$id'
      fullPath: '/client/projects/$id'
      preLoaderRoute: typeof ClientProjectsIdRouteImport
      parentRoute: typeof ClientProjectsRoute
    }
    '/chamados/$id/editar': {
      id: '/chamados/$id/editar'
      path: '/editar'
      fullPath: '/chamados/$id/editar'
      preLoaderRoute: typeof ChamadosIdEditarRouteImport
      parentRoute: typeof ChamadosIdRoute
    }
    '/atividades/$id/editar': {
      id: '/atividades/$id/editar'
      path: '/editar'
      fullPath: '/atividades/$id/editar'
      preLoaderRoute: typeof AtividadesIdEditarRouteImport
      parentRoute: typeof AtividadesIdRoute
    }
    '/activities/$id/edit': {
      id: '/activities/$id/edit'
      path: '/edit'
      fullPath: '/activities/$id/edit'
      preLoaderRoute: typeof ActivitiesIdEditRouteImport
      parentRoute: typeof ActivitiesIdRoute
    }
  }
}

interface ActivitiesIdRouteChildren {
  ActivitiesIdEditRoute: typeof ActivitiesIdEditRoute
}

const ActivitiesIdRouteChildren: ActivitiesIdRouteChildren = {
  ActivitiesIdEditRoute: ActivitiesIdEditRoute,
}

const ActivitiesIdRouteWithChildren = ActivitiesIdRoute._addFileChildren(
  ActivitiesIdRouteChildren,
)

interface ActivitiesRouteChildren {
  ActivitiesIdRoute: typeof ActivitiesIdRouteWithChildren
  ActivitiesNewRoute: typeof ActivitiesNewRoute
}

const ActivitiesRouteChildren: ActivitiesRouteChildren = {
  ActivitiesIdRoute: ActivitiesIdRouteWithChildren,
  ActivitiesNewRoute: ActivitiesNewRoute,
}

const ActivitiesRouteWithChildren = ActivitiesRoute._addFileChildren(
  ActivitiesRouteChildren,
)

interface BacklogRouteChildren {
  BacklogNewRoute: typeof BacklogNewRoute
}

const BacklogRouteChildren: BacklogRouteChildren = {
  BacklogNewRoute: BacklogNewRoute,
}

const BacklogRouteWithChildren =
  BacklogRoute._addFileChildren(BacklogRouteChildren)

interface ClientProjectsRouteChildren {
  ClientProjectsIdRoute: typeof ClientProjectsIdRoute
}

const ClientProjectsRouteChildren: ClientProjectsRouteChildren = {
  ClientProjectsIdRoute: ClientProjectsIdRoute,
}

const ClientProjectsRouteWithChildren = ClientProjectsRoute._addFileChildren(
  ClientProjectsRouteChildren,
)

interface ClientTicketsRouteChildren {
  ClientTicketsIdRoute: typeof ClientTicketsIdRoute
  ClientTicketsNewRoute: typeof ClientTicketsNewRoute
}

const ClientTicketsRouteChildren: ClientTicketsRouteChildren = {
  ClientTicketsIdRoute: ClientTicketsIdRoute,
  ClientTicketsNewRoute: ClientTicketsNewRoute,
}

const ClientTicketsRouteWithChildren = ClientTicketsRoute._addFileChildren(
  ClientTicketsRouteChildren,
)

interface ClientRouteChildren {
  ClientProjectsRoute: typeof ClientProjectsRouteWithChildren
  ClientTicketsRoute: typeof ClientTicketsRouteWithChildren
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientProjectsRoute: ClientProjectsRouteWithChildren,
  ClientTicketsRoute: ClientTicketsRouteWithChildren,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface ClientsIdRouteChildren {
  ClientsIdEditRoute: typeof ClientsIdEditRoute
}

const ClientsIdRouteChildren: ClientsIdRouteChildren = {
  ClientsIdEditRoute: ClientsIdEditRoute,
}

const ClientsIdRouteWithChildren = ClientsIdRoute._addFileChildren(
  ClientsIdRouteChildren,
)

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRouteWithChildren
  ClientsNewRoute: typeof ClientsNewRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRouteWithChildren,
  ClientsNewRoute: ClientsNewRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface ProjectsIdRouteChildren {
  ProjectsIdEditRoute: typeof ProjectsIdEditRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdEditRoute: ProjectsIdEditRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SprintsIdRouteChildren {
  SprintsIdEditRoute: typeof SprintsIdEditRoute
  SprintsIdEditarRoute: typeof SprintsIdEditarRoute
}

const SprintsIdRouteChildren: SprintsIdRouteChildren = {
  SprintsIdEditRoute: SprintsIdEditRoute,
  SprintsIdEditarRoute: SprintsIdEditarRoute,
}

const SprintsIdRouteWithChildren = SprintsIdRoute._addFileChildren(
  SprintsIdRouteChildren,
)

interface SprintsRouteChildren {
  SprintsIdRoute: typeof SprintsIdRouteWithChildren
  SprintsNewRoute: typeof SprintsNewRoute
  SprintsNovaRoute: typeof SprintsNovaRoute
}

const SprintsRouteChildren: SprintsRouteChildren = {
  SprintsIdRoute: SprintsIdRouteWithChildren,
  SprintsNewRoute: SprintsNewRoute,
  SprintsNovaRoute: SprintsNovaRoute,
}

const SprintsRouteWithChildren =
  SprintsRoute._addFileChildren(SprintsRouteChildren)

interface TeamsIdRouteChildren {
  TeamsIdEditRoute: typeof TeamsIdEditRoute
}

const TeamsIdRouteChildren: TeamsIdRouteChildren = {
  TeamsIdEditRoute: TeamsIdEditRoute,
}

const TeamsIdRouteWithChildren =
  TeamsIdRoute._addFileChildren(TeamsIdRouteChildren)

interface TeamsRouteChildren {
  TeamsIdRoute: typeof TeamsIdRouteWithChildren
  TeamsNewRoute: typeof TeamsNewRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsIdRoute: TeamsIdRouteWithChildren,
  TeamsNewRoute: TeamsNewRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface TicketsIdRouteChildren {
  TicketsIdEditRoute: typeof TicketsIdEditRoute
}

const TicketsIdRouteChildren: TicketsIdRouteChildren = {
  TicketsIdEditRoute: TicketsIdEditRoute,
}

const TicketsIdRouteWithChildren = TicketsIdRoute._addFileChildren(
  TicketsIdRouteChildren,
)

interface TicketsRouteChildren {
  TicketsIdRoute: typeof TicketsIdRouteWithChildren
  TicketsNewRoute: typeof TicketsNewRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsIdRoute: TicketsIdRouteWithChildren,
  TicketsNewRoute: TicketsNewRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

interface AtividadesIdRouteChildren {
  AtividadesIdEditarRoute: typeof AtividadesIdEditarRoute
}

const AtividadesIdRouteChildren: AtividadesIdRouteChildren = {
  AtividadesIdEditarRoute: AtividadesIdEditarRoute,
}

const AtividadesIdRouteWithChildren = AtividadesIdRoute._addFileChildren(
  AtividadesIdRouteChildren,
)

interface ChamadosIdRouteChildren {
  ChamadosIdEditarRoute: typeof ChamadosIdEditarRoute
}

const ChamadosIdRouteChildren: ChamadosIdRouteChildren = {
  ChamadosIdEditarRoute: ChamadosIdEditarRoute,
}

const ChamadosIdRouteWithChildren = ChamadosIdRoute._addFileChildren(
  ChamadosIdRouteChildren,
)

interface ProjetosIdRouteChildren {
  ProjetosIdEditarRoute: typeof ProjetosIdEditarRoute
}

const ProjetosIdRouteChildren: ProjetosIdRouteChildren = {
  ProjetosIdEditarRoute: ProjetosIdEditarRoute,
}

const ProjetosIdRouteWithChildren = ProjetosIdRoute._addFileChildren(
  ProjetosIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRouteWithChildren,
  BacklogRoute: BacklogRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  ClientsRoute: ClientsRouteWithChildren,
  KanbanRoute: KanbanRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SprintsRoute: SprintsRouteWithChildren,
  TeamsRoute: TeamsRouteWithChildren,
  TicketCategoriesRoute: TicketCategoriesRoute,
  TicketsRoute: TicketsRouteWithChildren,
  AtividadesIdRoute: AtividadesIdRouteWithChildren,
  AtividadesNovaRoute: AtividadesNovaRoute,
  ChamadosIdRoute: ChamadosIdRouteWithChildren,
  ChamadosNovoRoute: ChamadosNovoRoute,
  ProjetosIdRoute: ProjetosIdRouteWithChildren,
  ProjetosNovoRoute: ProjetosNovoRoute,
  AtividadesIndexRoute: AtividadesIndexRoute,
  ChamadosIndexRoute: ChamadosIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
