/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebhooksRouteImport } from './routes/webhooks'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TicketCategoriesRouteImport } from './routes/ticket-categories'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SprintsRouteImport } from './routes/sprints'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PermissionBlocksRouteImport } from './routes/permission-blocks'
import { Route as OrgRouteImport } from './routes/org'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationPreferencesRouteImport } from './routes/notification-preferences'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as KnowledgeCategoriesRouteImport } from './routes/knowledge-categories'
import { Route as ForumCategoriesRouteImport } from './routes/forum-categories'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmailTemplatesRouteImport } from './routes/email-templates'
import { Route as DoubtsRouteImport } from './routes/doubts'
import { Route as DashboardBuilderRouteImport } from './routes/dashboard-builder'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ClientRouteImport } from './routes/client'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as BacklogRouteImport } from './routes/backlog'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AprovacoesRouteImport } from './routes/aprovacoes'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ChamadosIndexRouteImport } from './routes/chamados.index'
import { Route as AtividadesIndexRouteImport } from './routes/atividades.index'
import { Route as TicketsNewRouteImport } from './routes/tickets.new'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as TeamsNewRouteImport } from './routes/teams.new'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as SprintsNovaRouteImport } from './routes/sprints.nova'
import { Route as SprintsNewRouteImport } from './routes/sprints.new'
import { Route as SprintsIdRouteImport } from './routes/sprints.$id'
import { Route as ProjetosNovoRouteImport } from './routes/projetos.novo'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as KnowledgeNewRouteImport } from './routes/knowledge.new'
import { Route as KnowledgeIdRouteImport } from './routes/knowledge.$id'
import { Route as ForumIdRouteImport } from './routes/forum.$id'
import { Route as DoubtsIdRouteImport } from './routes/doubts.$id'
import { Route as ClientsNewRouteImport } from './routes/clients.new'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as ClientTicketsRouteImport } from './routes/client.tickets'
import { Route as ClientProjectsRouteImport } from './routes/client.projects'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as ChamadosNovoRouteImport } from './routes/chamados.novo'
import { Route as ChamadosIdRouteImport } from './routes/chamados.$id'
import { Route as BacklogNewRouteImport } from './routes/backlog.new'
import { Route as AtividadesNovaRouteImport } from './routes/atividades.nova'
import { Route as AtividadesIdRouteImport } from './routes/atividades.$id'
import { Route as ActivitiesNewRouteImport } from './routes/activities.new'
import { Route as ActivitiesIdRouteImport } from './routes/activities.$id'
import { Route as TicketsIdEditRouteImport } from './routes/tickets.$id.edit'
import { Route as TeamsIdEditRouteImport } from './routes/teams.$id.edit'
import { Route as SprintsIdEditarRouteImport } from './routes/sprints.$id.editar'
import { Route as SprintsIdEditRouteImport } from './routes/sprints.$id.edit'
import { Route as ProjetosIdEditarRouteImport } from './routes/projetos.$id.editar'
import { Route as ProjectsIdEditRouteImport } from './routes/projects.$id.edit'
import { Route as KnowledgeIdEditRouteImport } from './routes/knowledge.$id.edit'
import { Route as ClientsIdEditRouteImport } from './routes/clients.$id.edit'
import { Route as ClientTicketsNewRouteImport } from './routes/client.tickets.new'
import { Route as ClientTicketsIdRouteImport } from './routes/client.tickets.$id'
import { Route as ClientProjectsIdRouteImport } from './routes/client.projects.$id'
import { Route as ChamadosIdEditarRouteImport } from './routes/chamados.$id.editar'
import { Route as AtividadesIdEditarRouteImport } from './routes/atividades.$id.editar'
import { Route as ActivitiesIdEditRouteImport } from './routes/activities.$id.edit'

const WebhooksRoute = WebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketCategoriesRoute = TicketCategoriesRouteImport.update({
  id: '/ticket-categories',
  path: '/ticket-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SprintsRoute = SprintsRouteImport.update({
  id: '/sprints',
  path: '/sprints',
  getParentRoute: () => rootRouteImport,
} as any)
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionBlocksRoute = PermissionBlocksRouteImport.update({
  id: '/permission-blocks',
  path: '/permission-blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationPreferencesRoute = NotificationPreferencesRouteImport.update({
  id: '/notification-preferences',
  path: '/notification-preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeCategoriesRoute = KnowledgeCategoriesRouteImport.update({
  id: '/knowledge-categories',
  path: '/knowledge-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumCategoriesRoute = ForumCategoriesRouteImport.update({
  id: '/forum-categories',
  path: '/forum-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplatesRoute = EmailTemplatesRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubtsRoute = DoubtsRouteImport.update({
  id: '/doubts',
  path: '/doubts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuilderRoute = DashboardBuilderRouteImport.update({
  id: '/dashboard-builder',
  path: '/dashboard-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRoute = BacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovacoesRoute = AprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosIndexRoute = ChamadosIndexRouteImport.update({
  id: '/chamados/',
  path: '/chamados/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesIndexRoute = AtividadesIndexRouteImport.update({
  id: '/atividades/',
  path: '/atividades/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsNewRoute = TicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TicketsRoute,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketsRoute,
} as any)
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TeamsRoute,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeamsRoute,
} as any)
const SprintsNovaRoute = SprintsNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => SprintsRoute,
} as any)
const SprintsNewRoute = SprintsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SprintsRoute,
} as any)
const SprintsIdRoute = SprintsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SprintsRoute,
} as any)
const ProjetosNovoRoute = ProjetosNovoRouteImport.update({
  id: '/projetos/novo',
  path: '/projetos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const KnowledgeNewRoute = KnowledgeNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeIdRoute = KnowledgeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ForumIdRoute = ForumIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ForumRoute,
} as any)
const DoubtsIdRoute = DoubtsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DoubtsRoute,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientTicketsRoute = ClientTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProjectsRoute = ClientProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ClientRoute,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ClientRoute,
} as any)
const ChamadosNovoRoute = ChamadosNovoRouteImport.update({
  id: '/chamados/novo',
  path: '/chamados/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosIdRoute = ChamadosIdRouteImport.update({
  id: '/chamados/$id',
  path: '/chamados/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogNewRoute = BacklogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BacklogRoute,
} as any)
const AtividadesNovaRoute = AtividadesNovaRouteImport.update({
  id: '/atividades/nova',
  path: '/atividades/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadesIdRoute = AtividadesIdRouteImport.update({
  id: '/atividades/$id',
  path: '/atividades/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesNewRoute = ActivitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ActivitiesRoute,
} as any)
const ActivitiesIdRoute = ActivitiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ActivitiesRoute,
} as any)
const TicketsIdEditRoute = TicketsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TicketsIdRoute,
} as any)
const TeamsIdEditRoute = TeamsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TeamsIdRoute,
} as any)
const SprintsIdEditarRoute = SprintsIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => SprintsIdRoute,
} as any)
const SprintsIdEditRoute = SprintsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => SprintsIdRoute,
} as any)
const ProjetosIdEditarRoute = ProjetosIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ProjetosIdRoute,
} as any)
const ProjectsIdEditRoute = ProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const KnowledgeIdEditRoute = KnowledgeIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => KnowledgeIdRoute,
} as any)
const ClientsIdEditRoute = ClientsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ClientsIdRoute,
} as any)
const ClientTicketsNewRoute = ClientTicketsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClientTicketsRoute,
} as any)
const ClientTicketsIdRoute = ClientTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientTicketsRoute,
} as any)
const ClientProjectsIdRoute = ClientProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientProjectsRoute,
} as any)
const ChamadosIdEditarRoute = ChamadosIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => ChamadosIdRoute,
} as any)
const AtividadesIdEditarRoute = AtividadesIdEditarRouteImport.update({
  id: '/editar',
  path: '/editar',
  getParentRoute: () => AtividadesIdRoute,
} as any)
const ActivitiesIdEditRoute = ActivitiesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ActivitiesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/aprovacoes': typeof AprovacoesRoute
  '/audit': typeof AuditRoute
  '/backlog': typeof BacklogRouteWithChildren
  '/chat': typeof ChatRoute
  '/client': typeof ClientRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard-builder': typeof DashboardBuilderRoute
  '/doubts': typeof DoubtsRouteWithChildren
  '/email-templates': typeof EmailTemplatesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forum': typeof ForumRouteWithChildren
  '/forum-categories': typeof ForumCategoriesRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/knowledge-categories': typeof KnowledgeCategoriesRoute
  '/login': typeof LoginRoute
  '/notification-preferences': typeof NotificationPreferencesRoute
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRoute
  '/permission-blocks': typeof PermissionBlocksRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sla': typeof SlaRoute
  '/sprints': typeof SprintsRouteWithChildren
  '/superadmin': typeof SuperadminRoute
  '/teams': typeof TeamsRouteWithChildren
  '/ticket-categories': typeof TicketCategoriesRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/webhooks': typeof WebhooksRoute
  '/activities/$id': typeof ActivitiesIdRouteWithChildren
  '/activities/new': typeof ActivitiesNewRoute
  '/atividades/$id': typeof AtividadesIdRouteWithChildren
  '/atividades/nova': typeof AtividadesNovaRoute
  '/backlog/new': typeof BacklogNewRoute
  '/chamados/$id': typeof ChamadosIdRouteWithChildren
  '/chamados/novo': typeof ChamadosNovoRoute
  '/client/login': typeof ClientLoginRoute
  '/client/projects': typeof ClientProjectsRouteWithChildren
  '/client/tickets': typeof ClientTicketsRouteWithChildren
  '/clients/$id': typeof ClientsIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/doubts/$id': typeof DoubtsIdRoute
  '/forum/$id': typeof ForumIdRoute
  '/knowledge/$id': typeof KnowledgeIdRouteWithChildren
  '/knowledge/new': typeof KnowledgeNewRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projetos/$id': typeof ProjetosIdRouteWithChildren
  '/projetos/novo': typeof ProjetosNovoRoute
  '/sprints/$id': typeof SprintsIdRouteWithChildren
  '/sprints/new': typeof SprintsNewRoute
  '/sprints/nova': typeof SprintsNovaRoute
  '/teams/$id': typeof TeamsIdRouteWithChildren
  '/teams/new': typeof TeamsNewRoute
  '/tickets/$id': typeof TicketsIdRouteWithChildren
  '/tickets/new': typeof TicketsNewRoute
  '/atividades/': typeof AtividadesIndexRoute
  '/chamados/': typeof ChamadosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/activities/$id/edit': typeof ActivitiesIdEditRoute
  '/atividades/$id/editar': typeof AtividadesIdEditarRoute
  '/chamados/$id/editar': typeof ChamadosIdEditarRoute
  '/client/projects/$id': typeof ClientProjectsIdRoute
  '/client/tickets/$id': typeof ClientTicketsIdRoute
  '/client/tickets/new': typeof ClientTicketsNewRoute
  '/clients/$id/edit': typeof ClientsIdEditRoute
  '/knowledge/$id/edit': typeof KnowledgeIdEditRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projetos/$id/editar': typeof ProjetosIdEditarRoute
  '/sprints/$id/edit': typeof SprintsIdEditRoute
  '/sprints/$id/editar': typeof SprintsIdEditarRoute
  '/teams/$id/edit': typeof TeamsIdEditRoute
  '/tickets/$id/edit': typeof TicketsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/aprovacoes': typeof AprovacoesRoute
  '/audit': typeof AuditRoute
  '/backlog': typeof BacklogRouteWithChildren
  '/chat': typeof ChatRoute
  '/client': typeof ClientRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard-builder': typeof DashboardBuilderRoute
  '/doubts': typeof DoubtsRouteWithChildren
  '/email-templates': typeof EmailTemplatesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forum': typeof ForumRouteWithChildren
  '/forum-categories': typeof ForumCategoriesRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/knowledge-categories': typeof KnowledgeCategoriesRoute
  '/login': typeof LoginRoute
  '/notification-preferences': typeof NotificationPreferencesRoute
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRoute
  '/permission-blocks': typeof PermissionBlocksRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sla': typeof SlaRoute
  '/sprints': typeof SprintsRouteWithChildren
  '/superadmin': typeof SuperadminRoute
  '/teams': typeof TeamsRouteWithChildren
  '/ticket-categories': typeof TicketCategoriesRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/webhooks': typeof WebhooksRoute
  '/activities/$id': typeof ActivitiesIdRouteWithChildren
  '/activities/new': typeof ActivitiesNewRoute
  '/atividades/$id': typeof AtividadesIdRouteWithChildren
  '/atividades/nova': typeof AtividadesNovaRoute
  '/backlog/new': typeof BacklogNewRoute
  '/chamados/$id': typeof ChamadosIdRouteWithChildren
  '/chamados/novo': typeof ChamadosNovoRoute
  '/client/login': typeof ClientLoginRoute
  '/client/projects': typeof ClientProjectsRouteWithChildren
  '/client/tickets': typeof ClientTicketsRouteWithChildren
  '/clients/$id': typeof ClientsIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/doubts/$id': typeof DoubtsIdRoute
  '/forum/$id': typeof ForumIdRoute
  '/knowledge/$id': typeof KnowledgeIdRouteWithChildren
  '/knowledge/new': typeof KnowledgeNewRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projetos/$id': typeof ProjetosIdRouteWithChildren
  '/projetos/novo': typeof ProjetosNovoRoute
  '/sprints/$id': typeof SprintsIdRouteWithChildren
  '/sprints/new': typeof SprintsNewRoute
  '/sprints/nova': typeof SprintsNovaRoute
  '/teams/$id': typeof TeamsIdRouteWithChildren
  '/teams/new': typeof TeamsNewRoute
  '/tickets/$id': typeof TicketsIdRouteWithChildren
  '/tickets/new': typeof TicketsNewRoute
  '/atividades': typeof AtividadesIndexRoute
  '/chamados': typeof ChamadosIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/activities/$id/edit': typeof ActivitiesIdEditRoute
  '/atividades/$id/editar': typeof AtividadesIdEditarRoute
  '/chamados/$id/editar': typeof ChamadosIdEditarRoute
  '/client/projects/$id': typeof ClientProjectsIdRoute
  '/client/tickets/$id': typeof ClientTicketsIdRoute
  '/client/tickets/new': typeof ClientTicketsNewRoute
  '/clients/$id/edit': typeof ClientsIdEditRoute
  '/knowledge/$id/edit': typeof KnowledgeIdEditRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projetos/$id/editar': typeof ProjetosIdEditarRoute
  '/sprints/$id/edit': typeof SprintsIdEditRoute
  '/sprints/$id/editar': typeof SprintsIdEditarRoute
  '/teams/$id/edit': typeof TeamsIdEditRoute
  '/tickets/$id/edit': typeof TicketsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/activities': typeof ActivitiesRouteWithChildren
  '/aprovacoes': typeof AprovacoesRoute
  '/audit': typeof AuditRoute
  '/backlog': typeof BacklogRouteWithChildren
  '/chat': typeof ChatRoute
  '/client': typeof ClientRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard-builder': typeof DashboardBuilderRoute
  '/doubts': typeof DoubtsRouteWithChildren
  '/email-templates': typeof EmailTemplatesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/forum': typeof ForumRouteWithChildren
  '/forum-categories': typeof ForumCategoriesRoute
  '/inbox': typeof InboxRoute
  '/kanban': typeof KanbanRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/knowledge-categories': typeof KnowledgeCategoriesRoute
  '/login': typeof LoginRoute
  '/notification-preferences': typeof NotificationPreferencesRoute
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRoute
  '/permission-blocks': typeof PermissionBlocksRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/sla': typeof SlaRoute
  '/sprints': typeof SprintsRouteWithChildren
  '/superadmin': typeof SuperadminRoute
  '/teams': typeof TeamsRouteWithChildren
  '/ticket-categories': typeof TicketCategoriesRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/webhooks': typeof WebhooksRoute
  '/activities/$id': typeof ActivitiesIdRouteWithChildren
  '/activities/new': typeof ActivitiesNewRoute
  '/atividades/$id': typeof AtividadesIdRouteWithChildren
  '/atividades/nova': typeof AtividadesNovaRoute
  '/backlog/new': typeof BacklogNewRoute
  '/chamados/$id': typeof ChamadosIdRouteWithChildren
  '/chamados/novo': typeof ChamadosNovoRoute
  '/client/login': typeof ClientLoginRoute
  '/client/projects': typeof ClientProjectsRouteWithChildren
  '/client/tickets': typeof ClientTicketsRouteWithChildren
  '/clients/$id': typeof ClientsIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/doubts/$id': typeof DoubtsIdRoute
  '/forum/$id': typeof ForumIdRoute
  '/knowledge/$id': typeof KnowledgeIdRouteWithChildren
  '/knowledge/new': typeof KnowledgeNewRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/projetos/$id': typeof ProjetosIdRouteWithChildren
  '/projetos/novo': typeof ProjetosNovoRoute
  '/sprints/$id': typeof SprintsIdRouteWithChildren
  '/sprints/new': typeof SprintsNewRoute
  '/sprints/nova': typeof SprintsNovaRoute
  '/teams/$id': typeof TeamsIdRouteWithChildren
  '/teams/new': typeof TeamsNewRoute
  '/tickets/$id': typeof TicketsIdRouteWithChildren
  '/tickets/new': typeof TicketsNewRoute
  '/atividades/': typeof AtividadesIndexRoute
  '/chamados/': typeof ChamadosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/activities/$id/edit': typeof ActivitiesIdEditRoute
  '/atividades/$id/editar': typeof AtividadesIdEditarRoute
  '/chamados/$id/editar': typeof ChamadosIdEditarRoute
  '/client/projects/$id': typeof ClientProjectsIdRoute
  '/client/tickets/$id': typeof ClientTicketsIdRoute
  '/client/tickets/new': typeof ClientTicketsNewRoute
  '/clients/$id/edit': typeof ClientsIdEditRoute
  '/knowledge/$id/edit': typeof KnowledgeIdEditRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
  '/projetos/$id/editar': typeof ProjetosIdEditarRoute
  '/sprints/$id/edit': typeof SprintsIdEditRoute
  '/sprints/$id/editar': typeof SprintsIdEditarRoute
  '/teams/$id/edit': typeof TeamsIdEditRoute
  '/tickets/$id/edit': typeof TicketsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/activities'
    | '/aprovacoes'
    | '/audit'
    | '/backlog'
    | '/chat'
    | '/client'
    | '/clients'
    | '/dashboard-builder'
    | '/doubts'
    | '/email-templates'
    | '/forgot-password'
    | '/forum'
    | '/forum-categories'
    | '/inbox'
    | '/kanban'
    | '/knowledge'
    | '/knowledge-categories'
    | '/login'
    | '/notification-preferences'
    | '/onboarding'
    | '/org'
    | '/permission-blocks'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/sla'
    | '/sprints'
    | '/superadmin'
    | '/teams'
    | '/ticket-categories'
    | '/tickets'
    | '/webhooks'
    | '/activities/$id'
    | '/activities/new'
    | '/atividades/$id'
    | '/atividades/nova'
    | '/backlog/new'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/client/login'
    | '/client/projects'
    | '/client/tickets'
    | '/clients/$id'
    | '/clients/new'
    | '/doubts/$id'
    | '/forum/$id'
    | '/knowledge/$id'
    | '/knowledge/new'
    | '/projects/$id'
    | '/projects/new'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/sprints/$id'
    | '/sprints/new'
    | '/sprints/nova'
    | '/teams/$id'
    | '/teams/new'
    | '/tickets/$id'
    | '/tickets/new'
    | '/atividades/'
    | '/chamados/'
    | '/projetos/'
    | '/activities/$id/edit'
    | '/atividades/$id/editar'
    | '/chamados/$id/editar'
    | '/client/projects/$id'
    | '/client/tickets/$id'
    | '/client/tickets/new'
    | '/clients/$id/edit'
    | '/knowledge/$id/edit'
    | '/projects/$id/edit'
    | '/projetos/$id/editar'
    | '/sprints/$id/edit'
    | '/sprints/$id/editar'
    | '/teams/$id/edit'
    | '/tickets/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/activities'
    | '/aprovacoes'
    | '/audit'
    | '/backlog'
    | '/chat'
    | '/client'
    | '/clients'
    | '/dashboard-builder'
    | '/doubts'
    | '/email-templates'
    | '/forgot-password'
    | '/forum'
    | '/forum-categories'
    | '/inbox'
    | '/kanban'
    | '/knowledge'
    | '/knowledge-categories'
    | '/login'
    | '/notification-preferences'
    | '/onboarding'
    | '/org'
    | '/permission-blocks'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/sla'
    | '/sprints'
    | '/superadmin'
    | '/teams'
    | '/ticket-categories'
    | '/tickets'
    | '/webhooks'
    | '/activities/$id'
    | '/activities/new'
    | '/atividades/$id'
    | '/atividades/nova'
    | '/backlog/new'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/client/login'
    | '/client/projects'
    | '/client/tickets'
    | '/clients/$id'
    | '/clients/new'
    | '/doubts/$id'
    | '/forum/$id'
    | '/knowledge/$id'
    | '/knowledge/new'
    | '/projects/$id'
    | '/projects/new'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/sprints/$id'
    | '/sprints/new'
    | '/sprints/nova'
    | '/teams/$id'
    | '/teams/new'
    | '/tickets/$id'
    | '/tickets/new'
    | '/atividades'
    | '/chamados'
    | '/projetos'
    | '/activities/$id/edit'
    | '/atividades/$id/editar'
    | '/chamados/$id/editar'
    | '/client/projects/$id'
    | '/client/tickets/$id'
    | '/client/tickets/new'
    | '/clients/$id/edit'
    | '/knowledge/$id/edit'
    | '/projects/$id/edit'
    | '/projetos/$id/editar'
    | '/sprints/$id/edit'
    | '/sprints/$id/editar'
    | '/teams/$id/edit'
    | '/tickets/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/activities'
    | '/aprovacoes'
    | '/audit'
    | '/backlog'
    | '/chat'
    | '/client'
    | '/clients'
    | '/dashboard-builder'
    | '/doubts'
    | '/email-templates'
    | '/forgot-password'
    | '/forum'
    | '/forum-categories'
    | '/inbox'
    | '/kanban'
    | '/knowledge'
    | '/knowledge-categories'
    | '/login'
    | '/notification-preferences'
    | '/onboarding'
    | '/org'
    | '/permission-blocks'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/sla'
    | '/sprints'
    | '/superadmin'
    | '/teams'
    | '/ticket-categories'
    | '/tickets'
    | '/webhooks'
    | '/activities/$id'
    | '/activities/new'
    | '/atividades/$id'
    | '/atividades/nova'
    | '/backlog/new'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/client/login'
    | '/client/projects'
    | '/client/tickets'
    | '/clients/$id'
    | '/clients/new'
    | '/doubts/$id'
    | '/forum/$id'
    | '/knowledge/$id'
    | '/knowledge/new'
    | '/projects/$id'
    | '/projects/new'
    | '/projetos/$id'
    | '/projetos/novo'
    | '/sprints/$id'
    | '/sprints/new'
    | '/sprints/nova'
    | '/teams/$id'
    | '/teams/new'
    | '/tickets/$id'
    | '/tickets/new'
    | '/atividades/'
    | '/chamados/'
    | '/projetos/'
    | '/activities/$id/edit'
    | '/atividades/$id/editar'
    | '/chamados/$id/editar'
    | '/client/projects/$id'
    | '/client/tickets/$id'
    | '/client/tickets/new'
    | '/clients/$id/edit'
    | '/knowledge/$id/edit'
    | '/projects/$id/edit'
    | '/projetos/$id/editar'
    | '/sprints/$id/edit'
    | '/sprints/$id/editar'
    | '/teams/$id/edit'
    | '/tickets/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  ActivitiesRoute: typeof ActivitiesRouteWithChildren
  AprovacoesRoute: typeof AprovacoesRoute
  AuditRoute: typeof AuditRoute
  BacklogRoute: typeof BacklogRouteWithChildren
  ChatRoute: typeof ChatRoute
  ClientRoute: typeof ClientRouteWithChildren
  ClientsRoute: typeof ClientsRouteWithChildren
  DashboardBuilderRoute: typeof DashboardBuilderRoute
  DoubtsRoute: typeof DoubtsRouteWithChildren
  EmailTemplatesRoute: typeof EmailTemplatesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ForumRoute: typeof ForumRouteWithChildren
  ForumCategoriesRoute: typeof ForumCategoriesRoute
  InboxRoute: typeof InboxRoute
  KanbanRoute: typeof KanbanRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  KnowledgeCategoriesRoute: typeof KnowledgeCategoriesRoute
  LoginRoute: typeof LoginRoute
  NotificationPreferencesRoute: typeof NotificationPreferencesRoute
  OnboardingRoute: typeof OnboardingRoute
  OrgRoute: typeof OrgRoute
  PermissionBlocksRoute: typeof PermissionBlocksRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SlaRoute: typeof SlaRoute
  SprintsRoute: typeof SprintsRouteWithChildren
  SuperadminRoute: typeof SuperadminRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TicketCategoriesRoute: typeof TicketCategoriesRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  WebhooksRoute: typeof WebhooksRoute
  AtividadesIdRoute: typeof AtividadesIdRouteWithChildren
  AtividadesNovaRoute: typeof AtividadesNovaRoute
  ChamadosIdRoute: typeof ChamadosIdRouteWithChildren
  ChamadosNovoRoute: typeof ChamadosNovoRoute
  ProjetosIdRoute: typeof ProjetosIdRouteWithChildren
  ProjetosNovoRoute: typeof ProjetosNovoRoute
  AtividadesIndexRoute: typeof AtividadesIndexRoute
  ChamadosIndexRoute: typeof ChamadosIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/webhooks': {
      id: '/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof WebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket-categories': {
      id: '/ticket-categories'
      path: '/ticket-categories'
      fullPath: '/ticket-categories'
      preLoaderRoute: typeof TicketCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sprints': {
      id: '/sprints'
      path: '/sprints'
      fullPath: '/sprints'
      preLoaderRoute: typeof SprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permission-blocks': {
      id: '/permission-blocks'
      path: '/permission-blocks'
      fullPath: '/permission-blocks'
      preLoaderRoute: typeof PermissionBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-preferences': {
      id: '/notification-preferences'
      path: '/notification-preferences'
      fullPath: '/notification-preferences'
      preLoaderRoute: typeof NotificationPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-categories': {
      id: '/knowledge-categories'
      path: '/knowledge-categories'
      fullPath: '/knowledge-categories'
      preLoaderRoute: typeof KnowledgeCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum-categories': {
      id: '/forum-categories'
      path: '/forum-categories'
      fullPath: '/forum-categories'
      preLoaderRoute: typeof ForumCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-templates': {
      id: '/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof EmailTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doubts': {
      id: '/doubts'
      path: '/doubts'
      fullPath: '/doubts'
      preLoaderRoute: typeof DoubtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-builder': {
      id: '/dashboard-builder'
      path: '/dashboard-builder'
      fullPath: '/dashboard-builder'
      preLoaderRoute: typeof DashboardBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovacoes': {
      id: '/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AprovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados/': {
      id: '/chamados/'
      path: '/chamados'
      fullPath: '/chamados/'
      preLoaderRoute: typeof ChamadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/': {
      id: '/atividades/'
      path: '/atividades'
      fullPath: '/atividades/'
      preLoaderRoute: typeof AtividadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/new': {
      id: '/tickets/new'
      path: '/new'
      fullPath: '/tickets/new'
      preLoaderRoute: typeof TicketsNewRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/teams/new': {
      id: '/teams/new'
      path: '/new'
      fullPath: '/teams/new'
      preLoaderRoute: typeof TeamsNewRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/sprints/nova': {
      id: '/sprints/nova'
      path: '/nova'
      fullPath: '/sprints/nova'
      preLoaderRoute: typeof SprintsNovaRouteImport
      parentRoute: typeof SprintsRoute
    }
    '/sprints/new': {
      id: '/sprints/new'
      path: '/new'
      fullPath: '/sprints/new'
      preLoaderRoute: typeof SprintsNewRouteImport
      parentRoute: typeof SprintsRoute
    }
    '/sprints/$id': {
      id: '/sprints/$id'
      path: '/$id'
      fullPath: '/sprints/$id'
      preLoaderRoute: typeof SprintsIdRouteImport
      parentRoute: typeof SprintsRoute
    }
    '/projetos/novo': {
      id: '/projetos/novo'
      path: '/projetos/novo'
      fullPath: '/projetos/novo'
      preLoaderRoute: typeof ProjetosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/knowledge/new': {
      id: '/knowledge/new'
      path: '/new'
      fullPath: '/knowledge/new'
      preLoaderRoute: typeof KnowledgeNewRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/$id': {
      id: '/knowledge/$id'
      path: '/$id'
      fullPath: '/knowledge/$id'
      preLoaderRoute: typeof KnowledgeIdRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/forum/$id': {
      id: '/forum/$id'
      path: '/$id'
      fullPath: '/forum/$id'
      preLoaderRoute: typeof ForumIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/doubts/$id': {
      id: '/doubts/$id'
      path: '/$id'
      fullPath: '/doubts/$id'
      preLoaderRoute: typeof DoubtsIdRouteImport
      parentRoute: typeof DoubtsRoute
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/client/tickets': {
      id: '/client/tickets'
      path: '/tickets'
      fullPath: '/client/tickets'
      preLoaderRoute: typeof ClientTicketsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/projects': {
      id: '/client/projects'
      path: '/projects'
      fullPath: '/client/projects'
      preLoaderRoute: typeof ClientProjectsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/login': {
      id: '/client/login'
      path: '/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof ClientRoute
    }
    '/chamados/novo': {
      id: '/chamados/novo'
      path: '/chamados/novo'
      fullPath: '/chamados/novo'
      preLoaderRoute: typeof ChamadosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados/$id': {
      id: '/chamados/$id'
      path: '/chamados/$id'
      fullPath: '/chamados/$id'
      preLoaderRoute: typeof ChamadosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog/new': {
      id: '/backlog/new'
      path: '/new'
      fullPath: '/backlog/new'
      preLoaderRoute: typeof BacklogNewRouteImport
      parentRoute: typeof BacklogRoute
    }
    '/atividades/nova': {
      id: '/atividades/nova'
      path: '/atividades/nova'
      fullPath: '/atividades/nova'
      preLoaderRoute: typeof AtividadesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividades/$id': {
      id: '/atividades/$id'
      path: '/atividades/$id'
      fullPath: '/atividades/$id'
      preLoaderRoute: typeof AtividadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/new': {
      id: '/activities/new'
      path: '/new'
      fullPath: '/activities/new'
      preLoaderRoute: typeof ActivitiesNewRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/activities/$id': {
      id: '/activities/$id'
      path: '/$id'
      fullPath: '/activities/$id'
      preLoaderRoute: typeof ActivitiesIdRouteImport
      parentRoute: typeof ActivitiesRoute
    }
    '/tickets/$id/edit': {
      id: '/tickets/$id/edit'
      path: '/edit'
      fullPath: '/tickets/$id/edit'
      preLoaderRoute: typeof TicketsIdEditRouteImport
      parentRoute: typeof TicketsIdRoute
    }
    '/teams/$id/edit': {
      id: '/teams/$id/edit'
      path: '/edit'
      fullPath: '/teams/$id/edit'
      preLoaderRoute: typeof TeamsIdEditRouteImport
      parentRoute: typeof TeamsIdRoute
    }
    '/sprints/$id/editar': {
      id: '/sprints/$id/editar'
      path: '/editar'
      fullPath: '/sprints/$id/editar'
      preLoaderRoute: typeof SprintsIdEditarRouteImport
      parentRoute: typeof SprintsIdRoute
    }
    '/sprints/$id/edit': {
      id: '/sprints/$id/edit'
      path: '/edit'
      fullPath: '/sprints/$id/edit'
      preLoaderRoute: typeof SprintsIdEditRouteImport
      parentRoute: typeof SprintsIdRoute
    }
    '/projetos/$id/editar': {
      id: '/projetos/$id/editar'
      path: '/editar'
      fullPath: '/projetos/$id/editar'
      preLoaderRoute: typeof ProjetosIdEditarRouteImport
      parentRoute: typeof ProjetosIdRoute
    }
    '/projects/$id/edit': {
      id: '/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof ProjectsIdEditRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/knowledge/$id/edit': {
      id: '/knowledge/$id/edit'
      path: '/edit'
      fullPath: '/knowledge/$id/edit'
      preLoaderRoute: typeof KnowledgeIdEditRouteImport
      parentRoute: typeof KnowledgeIdRoute
    }
    '/clients/$id/edit': {
      id: '/clients/$id/edit'
      path: '/edit'
      fullPath: '/clients/$id/edit'
      preLoaderRoute: typeof ClientsIdEditRouteImport
      parentRoute: typeof ClientsIdRoute
    }
    '/client/tickets/new': {
      id: '/client/tickets/new'
      path: '/new'
      fullPath: '/client/tickets/new'
      preLoaderRoute: typeof ClientTicketsNewRouteImport
      parentRoute: typeof ClientTicketsRoute
    }
    '/client/tickets/$id': {
      id: '/client/tickets/$id'
      path: '/$id'
      fullPath: '/client/tickets/$id'
      preLoaderRoute: typeof ClientTicketsIdRouteImport
      parentRoute: typeof ClientTicketsRoute
    }
    '/client/projects/$id': {
      id: '/client/projects/$id'
      path: '/$id'
      fullPath: '/client/projects/$id'
      preLoaderRoute: typeof ClientProjectsIdRouteImport
      parentRoute: typeof ClientProjectsRoute
    }
    '/chamados/$id/editar': {
      id: '/chamados/$id/editar'
      path: '/editar'
      fullPath: '/chamados/$id/editar'
      preLoaderRoute: typeof ChamadosIdEditarRouteImport
      parentRoute: typeof ChamadosIdRoute
    }
    '/atividades/$id/editar': {
      id: '/atividades/$id/editar'
      path: '/editar'
      fullPath: '/atividades/$id/editar'
      preLoaderRoute: typeof AtividadesIdEditarRouteImport
      parentRoute: typeof AtividadesIdRoute
    }
    '/activities/$id/edit': {
      id: '/activities/$id/edit'
      path: '/edit'
      fullPath: '/activities/$id/edit'
      preLoaderRoute: typeof ActivitiesIdEditRouteImport
      parentRoute: typeof ActivitiesIdRoute
    }
  }
}

interface ActivitiesIdRouteChildren {
  ActivitiesIdEditRoute: typeof ActivitiesIdEditRoute
}

const ActivitiesIdRouteChildren: ActivitiesIdRouteChildren = {
  ActivitiesIdEditRoute: ActivitiesIdEditRoute,
}

const ActivitiesIdRouteWithChildren = ActivitiesIdRoute._addFileChildren(
  ActivitiesIdRouteChildren,
)

interface ActivitiesRouteChildren {
  ActivitiesIdRoute: typeof ActivitiesIdRouteWithChildren
  ActivitiesNewRoute: typeof ActivitiesNewRoute
}

const ActivitiesRouteChildren: ActivitiesRouteChildren = {
  ActivitiesIdRoute: ActivitiesIdRouteWithChildren,
  ActivitiesNewRoute: ActivitiesNewRoute,
}

const ActivitiesRouteWithChildren = ActivitiesRoute._addFileChildren(
  ActivitiesRouteChildren,
)

interface BacklogRouteChildren {
  BacklogNewRoute: typeof BacklogNewRoute
}

const BacklogRouteChildren: BacklogRouteChildren = {
  BacklogNewRoute: BacklogNewRoute,
}

const BacklogRouteWithChildren =
  BacklogRoute._addFileChildren(BacklogRouteChildren)

interface ClientProjectsRouteChildren {
  ClientProjectsIdRoute: typeof ClientProjectsIdRoute
}

const ClientProjectsRouteChildren: ClientProjectsRouteChildren = {
  ClientProjectsIdRoute: ClientProjectsIdRoute,
}

const ClientProjectsRouteWithChildren = ClientProjectsRoute._addFileChildren(
  ClientProjectsRouteChildren,
)

interface ClientTicketsRouteChildren {
  ClientTicketsIdRoute: typeof ClientTicketsIdRoute
  ClientTicketsNewRoute: typeof ClientTicketsNewRoute
}

const ClientTicketsRouteChildren: ClientTicketsRouteChildren = {
  ClientTicketsIdRoute: ClientTicketsIdRoute,
  ClientTicketsNewRoute: ClientTicketsNewRoute,
}

const ClientTicketsRouteWithChildren = ClientTicketsRoute._addFileChildren(
  ClientTicketsRouteChildren,
)

interface ClientRouteChildren {
  ClientLoginRoute: typeof ClientLoginRoute
  ClientProjectsRoute: typeof ClientProjectsRouteWithChildren
  ClientTicketsRoute: typeof ClientTicketsRouteWithChildren
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientLoginRoute: ClientLoginRoute,
  ClientProjectsRoute: ClientProjectsRouteWithChildren,
  ClientTicketsRoute: ClientTicketsRouteWithChildren,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface ClientsIdRouteChildren {
  ClientsIdEditRoute: typeof ClientsIdEditRoute
}

const ClientsIdRouteChildren: ClientsIdRouteChildren = {
  ClientsIdEditRoute: ClientsIdEditRoute,
}

const ClientsIdRouteWithChildren = ClientsIdRoute._addFileChildren(
  ClientsIdRouteChildren,
)

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRouteWithChildren
  ClientsNewRoute: typeof ClientsNewRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRouteWithChildren,
  ClientsNewRoute: ClientsNewRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface DoubtsRouteChildren {
  DoubtsIdRoute: typeof DoubtsIdRoute
}

const DoubtsRouteChildren: DoubtsRouteChildren = {
  DoubtsIdRoute: DoubtsIdRoute,
}

const DoubtsRouteWithChildren =
  DoubtsRoute._addFileChildren(DoubtsRouteChildren)

interface ForumRouteChildren {
  ForumIdRoute: typeof ForumIdRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumIdRoute: ForumIdRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

interface KnowledgeIdRouteChildren {
  KnowledgeIdEditRoute: typeof KnowledgeIdEditRoute
}

const KnowledgeIdRouteChildren: KnowledgeIdRouteChildren = {
  KnowledgeIdEditRoute: KnowledgeIdEditRoute,
}

const KnowledgeIdRouteWithChildren = KnowledgeIdRoute._addFileChildren(
  KnowledgeIdRouteChildren,
)

interface KnowledgeRouteChildren {
  KnowledgeIdRoute: typeof KnowledgeIdRouteWithChildren
  KnowledgeNewRoute: typeof KnowledgeNewRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeIdRoute: KnowledgeIdRouteWithChildren,
  KnowledgeNewRoute: KnowledgeNewRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface ProjectsIdRouteChildren {
  ProjectsIdEditRoute: typeof ProjectsIdEditRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdEditRoute: ProjectsIdEditRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SprintsIdRouteChildren {
  SprintsIdEditRoute: typeof SprintsIdEditRoute
  SprintsIdEditarRoute: typeof SprintsIdEditarRoute
}

const SprintsIdRouteChildren: SprintsIdRouteChildren = {
  SprintsIdEditRoute: SprintsIdEditRoute,
  SprintsIdEditarRoute: SprintsIdEditarRoute,
}

const SprintsIdRouteWithChildren = SprintsIdRoute._addFileChildren(
  SprintsIdRouteChildren,
)

interface SprintsRouteChildren {
  SprintsIdRoute: typeof SprintsIdRouteWithChildren
  SprintsNewRoute: typeof SprintsNewRoute
  SprintsNovaRoute: typeof SprintsNovaRoute
}

const SprintsRouteChildren: SprintsRouteChildren = {
  SprintsIdRoute: SprintsIdRouteWithChildren,
  SprintsNewRoute: SprintsNewRoute,
  SprintsNovaRoute: SprintsNovaRoute,
}

const SprintsRouteWithChildren =
  SprintsRoute._addFileChildren(SprintsRouteChildren)

interface TeamsIdRouteChildren {
  TeamsIdEditRoute: typeof TeamsIdEditRoute
}

const TeamsIdRouteChildren: TeamsIdRouteChildren = {
  TeamsIdEditRoute: TeamsIdEditRoute,
}

const TeamsIdRouteWithChildren =
  TeamsIdRoute._addFileChildren(TeamsIdRouteChildren)

interface TeamsRouteChildren {
  TeamsIdRoute: typeof TeamsIdRouteWithChildren
  TeamsNewRoute: typeof TeamsNewRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsIdRoute: TeamsIdRouteWithChildren,
  TeamsNewRoute: TeamsNewRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface TicketsIdRouteChildren {
  TicketsIdEditRoute: typeof TicketsIdEditRoute
}

const TicketsIdRouteChildren: TicketsIdRouteChildren = {
  TicketsIdEditRoute: TicketsIdEditRoute,
}

const TicketsIdRouteWithChildren = TicketsIdRoute._addFileChildren(
  TicketsIdRouteChildren,
)

interface TicketsRouteChildren {
  TicketsIdRoute: typeof TicketsIdRouteWithChildren
  TicketsNewRoute: typeof TicketsNewRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsIdRoute: TicketsIdRouteWithChildren,
  TicketsNewRoute: TicketsNewRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

interface AtividadesIdRouteChildren {
  AtividadesIdEditarRoute: typeof AtividadesIdEditarRoute
}

const AtividadesIdRouteChildren: AtividadesIdRouteChildren = {
  AtividadesIdEditarRoute: AtividadesIdEditarRoute,
}

const AtividadesIdRouteWithChildren = AtividadesIdRoute._addFileChildren(
  AtividadesIdRouteChildren,
)

interface ChamadosIdRouteChildren {
  ChamadosIdEditarRoute: typeof ChamadosIdEditarRoute
}

const ChamadosIdRouteChildren: ChamadosIdRouteChildren = {
  ChamadosIdEditarRoute: ChamadosIdEditarRoute,
}

const ChamadosIdRouteWithChildren = ChamadosIdRoute._addFileChildren(
  ChamadosIdRouteChildren,
)

interface ProjetosIdRouteChildren {
  ProjetosIdEditarRoute: typeof ProjetosIdEditarRoute
}

const ProjetosIdRouteChildren: ProjetosIdRouteChildren = {
  ProjetosIdEditarRoute: ProjetosIdEditarRoute,
}

const ProjetosIdRouteWithChildren = ProjetosIdRoute._addFileChildren(
  ProjetosIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  ActivitiesRoute: ActivitiesRouteWithChildren,
  AprovacoesRoute: AprovacoesRoute,
  AuditRoute: AuditRoute,
  BacklogRoute: BacklogRouteWithChildren,
  ChatRoute: ChatRoute,
  ClientRoute: ClientRouteWithChildren,
  ClientsRoute: ClientsRouteWithChildren,
  DashboardBuilderRoute: DashboardBuilderRoute,
  DoubtsRoute: DoubtsRouteWithChildren,
  EmailTemplatesRoute: EmailTemplatesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ForumRoute: ForumRouteWithChildren,
  ForumCategoriesRoute: ForumCategoriesRoute,
  InboxRoute: InboxRoute,
  KanbanRoute: KanbanRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  KnowledgeCategoriesRoute: KnowledgeCategoriesRoute,
  LoginRoute: LoginRoute,
  NotificationPreferencesRoute: NotificationPreferencesRoute,
  OnboardingRoute: OnboardingRoute,
  OrgRoute: OrgRoute,
  PermissionBlocksRoute: PermissionBlocksRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SlaRoute: SlaRoute,
  SprintsRoute: SprintsRouteWithChildren,
  SuperadminRoute: SuperadminRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TicketCategoriesRoute: TicketCategoriesRoute,
  TicketsRoute: TicketsRouteWithChildren,
  WebhooksRoute: WebhooksRoute,
  AtividadesIdRoute: AtividadesIdRouteWithChildren,
  AtividadesNovaRoute: AtividadesNovaRoute,
  ChamadosIdRoute: ChamadosIdRouteWithChildren,
  ChamadosNovoRoute: ChamadosNovoRoute,
  ProjetosIdRoute: ProjetosIdRouteWithChildren,
  ProjetosNovoRoute: ProjetosNovoRoute,
  AtividadesIndexRoute: AtividadesIndexRoute,
  ChamadosIndexRoute: ChamadosIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
